inventory2share/inventory/urls.py
from django.conf.urls.defaults import patterns, include, url
from inventory.inv.models import Item, Unit, Category, Inventory, InventoryEntry, InventoryType

from inventory.views import home
from inventory.inv.inventory_views import (
    inventory,
    inventory_view,
    inventory_pick,
)
from inventory.inv.shopping_list_views import (
    shoppinglist,
    shoppinglist_add,
    shoppinglist_pick,
    shoppinglist_view,
)

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

admin.site.register(Item)
admin.site.register(Unit)
admin.site.register(Category)
admin.site.register(Inventory)
admin.site.register(InventoryEntry)
admin.site.register(InventoryType)

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'inventory.views.home', name='home'),
    # url(r'^inventory/', include('inventory.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^inv/$', home),
    url(r'^inventory/$', inventory),
    url(r'^shoppinglist/$', shoppinglist),
    url(r'^inventory/view/$', inventory_pick),
    url(r'^shoppinglist/view/$', shoppinglist_pick),
    
    url(r'^inventory/view/(\d+)/$', inventory_view),
    url(r'^shoppinglist/view/(\d+)/$', shoppinglist_view),
    
    url(r'^shoppinglist/add/$', shoppinglist_add),
)

inventory2share/inventory/inv/models.py
from django.db import models

class Unit(models.Model):
	name = models.CharField(max_length=50)
	plural_name = models.CharField(max_length=50)
	
	def __str__(self):
		return self.name
	
class Category(models.Model):
	name = models.CharField(max_length=50)
		
	def __str__(self):
		return self.name
	
class Item(models.Model):
	category 	= models.ForeignKey(Category)
	unit 		= models.ForeignKey(Unit)
	name 		= models.CharField(max_length=50)
	reorder_limit = models.PositiveIntegerField(max_length=3, null=True, blank=True)
	
	def __str__(self):
		return self.name

class InventoryType(models.Model):
	name 	= models.CharField(max_length=20)

	def __str__(self):
		return self.name    

class Inventory(models.Model):
	name 	= models.CharField(max_length=30)	
	items 	= models.ManyToManyField(Item, through='InventoryEntry')
	ttype	= models.ForeignKey(InventoryType)
	
	def __str__(self):
		return self.name
	
class ShoppingList(models.Model):
	name 	= models.CharField(max_length=30)	
	items 	= models.ManyToManyField(Item, through='ShoppingListEntry')
	
	def __str__(self):
		return self.name
		
class InventoryEntry(models.Model):
	item 		= models.ForeignKey(Item)
	inventory 	= models.ForeignKey(Inventory)
	isexist		= models.BooleanField()
	isreorder	= models.BooleanField()
	
	exist_quantity 	 = models.PositiveIntegerField(max_length=3, null=True, blank=True)
	reorder_quantity = models.PositiveIntegerField(max_length=3, null=True, blank=True)  
	
	def __str__(self):
		return "<%s %s %s of %s>" % (self.exist_quantity, self.reorder_quantity, self.item.unit, self.item.name)

class ShoppingListEntry(models.Model):
	item 		  = models.ForeignKey(Item)
	shopping_list = models.ForeignKey(ShoppingList)
	quantity 	  = models.PositiveIntegerField(max_length=3, null=True, blank=True)	  
	
	def __str__(self):
		return "<%s %s of %s>" % (self.quantity, self.item.unit, self.item.name)

inventory2share/inventory/inv/views.py
# Create your views here.

inventory2share/inventory/views.py
import logging
import collections
import settings

from django.template import RequestContext
from django.shortcuts import render_to_response

from util.customforms import InventoryForm
from inv.util import InventoryProcessor
from inv.models import (
    Item, 
    Inventory, 
    InventoryEntry, 
    InventoryType,
)
from inventory.inv.util import ParameterExtractor

logger = logging.getLogger(__name__)

#Helper functions



def home(request):
    csrfContext = RequestContext(request, {})
    return render_to_response('home.html', csrfContext)

inventory2share/templates/added_inventario.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Inventario</title></head>
	<body>
		<h1>Added items</h1>
		
		<p>Items</p>
		{{ items }}
	</body>
</html>

inventory2share/templates/book_list.html
<!DOCTYPE html>
<html lang="en">
	<head>
	<title>Future time</title>
	</head>
<body>
	<h1>My helpful timestamp site</h1>
	<p>Names: {{ names }} .</p>
	<hr>
	<p>Thanks for visiting my site.</p>
</body>
</html>

inventory2share/templates/current_datetime.html
<html><body>TEMPLATE: It is now {{ current_date }}.</body></html>

inventory2share/templates/home.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">		
		<script src="{{ STATIC_URL }}js-plugin/jquery-1.7.1.min.js"></script>
		<script src="{{ STATIC_URL }}js/home.js"></script>
		<link href="styles.css" rel="stylesheet">	
		<title>Home</title>
	</head>
	<body>
		<a href="/inventory/">Create inventory</a>
		<br>
		<a href="/inventory/view/">Open Inventory</a>
		<br>
		<a href="/shoppinglist/">Create Shopping List</a>
		<br>
		<a href="/shoppinglist/view/">Open Shopping List</a>
	</body>
</html>

inventory2share/templates/inventory.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<link href="{{ STATIC_URL }}css/inventory.css" rel="stylesheet">
		<title>Inventario</title>
	</head>		
	<body>
		<h2>Inventario</h2>
		<form action="/inventario/" method="POST" id="inventory">
			{% csrf_token %}
			{{ form.errors }}
						
			Name: {{ form.name }}
			
			<input type="submit" value="Use date" id="date">
			<input type="submit" value="Save">
			<input type="submit" name="SubmitTpl" value="Save as Template" >
			
			<p />
			<input type="radio" name="ttype" value="{{ simple_ttype.id }}" id="id_ttype_{{ simple_ttype.id }}" checked="yes">{{ simple_ttype.name }}
			<input type="radio" name="ttype" value="{{ detailed_ttype.id }}" id="id_ttype_{{ detailed_ttype.id }}">{{ detailed_ttype.name }}
			<p />
			<div id="form_canvas" class="table_container">
				<div class="row">
					<div class="cell">Exist</div>
					<div class="cell">Buy</div>
					<div class="cell">Category</div>
				</div>
				{% for category, items in categories.items %}
					<div  class="row" id="header">
						<div class="cell left">&nbsp;</div>
						<div class="cell middle">&nbsp;</div>
						<div class="cell right">{{ category }}</div>
					</div>
					{% for item in items %}
					<div class="row" id="entry_frame_{{item.id}}">
						<input type="checkbox" name="items" value="{{item.id}}" id="{{item.id}}" class="item">
						<div class="cell">							
							<input type="checkbox" name="isexist_{{item.id}}" value="True" id="isexist_{{item.id}}">
							<input type="text" name="qty_exist_{{item.id}}" id="qty_exist_{{item.id}}" size="3" maxlength="4" class="optional">
						</div>
						<div class="cell">
							<input type="checkbox" name="isreorder_{{item.id}}" value="True" id="isreorder_{{item.id}}">
							<input type="text" name="qty_reorder_{{item.id}}" id="qty_reorder_{{item.id}}" size="3" maxlength="4" class="optional">
						</div>
						<div class="cell">
							<span id="entry_canvas_{{item.id}}">
								<label class="optional">({{ item.unit }})</label>
								{{ item.name }}
							</span>
						</div>
					</div>
					{% endfor %}
				{% endfor %}
			</div>
			<p>
				<input type="submit" value="Load last" id="last">
				<input type="submit" value="Load AJAX" id="ajax">
				<input type="submit" name="SubmitTpl" value="Save as Template" >
				<input type="reset" value="Reset!">
				<input type="submit" value="Save">
			</p>
		</FORM>
		<div id="result">
			Area
		</div>
		<script src="{{ STATIC_URL }}js-plugin/jquery-1.7.1.min.js"></script>
		<script src="{{ STATIC_URL }}js/inventory_code.js"></script>
	</body>
</html>

inventory2share/templates/inventory_pick.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<script src="{{ STATIC_URL }}js-plugin/jquery-1.7.1.min.js"></script>
		<script src="{{ STATIC_URL }}js/inventory_code.js"></script>
		<style type="text/css">
		div {
			display: inline;
		}
		</style>
		<title>Inventory</title>
	</head>
	<body>
		<h1>View Inventory</h1>
		<ul>
		{% for inv in invs %}
			<li>			
				<a href="/inventario/view/{{ inv.id }}">{{ inv.name }}</a>
			</li>
		{% endfor %}
		</ul>
	</body>
</html>

inventory2share/templates/inventory_view.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<link href="{{ STATIC_URL }}css/inventory.css" rel="stylesheet">
		<title>Inventory</title>
	</head>
	<body id="inventario_view">
		<h2>Inventory: {{ inv.name }}</h2>
		{% if view != "Simple" %}
		<form action="." method="GET" id="inventory_view"> 
			<input type="submit" value="Toggle units" id="units">
			<input type="submit" value="Toggle qty" id="qty">
		</form>
		<br/>
		{% endif %}
		<div id="container" class="table_container">
			<div class="row" id="header">
				{% if view != "Simple" %}
					<span class="cell qty">Exist</span>
					<span class="cell qty">Buy</span>
					<span class="cell unit">Unit</span>
				{% endif %}
				<span class="cell name">Name</span>
			</div>
			{% for category, entries in results.items %}
				<div  class="row" id="header">
					<div class="cell left qty">&nbsp;</div>
					<div class="cell middle qty">&nbsp;</div>
					<div class="cell middle unit">&nbsp;</div>
					<div class="cell right">{{ category.name }}</div>
				</div>
				{% for entry in entries %}					
				<div class="row" id="entry_frame_{{item.id}}">
					{% if entry.exist_quantity %}
						<div class="cell qty">{{ entry.exist_quantity }}</div>
					{% else %}
						<div class="cell qty">&nbsp;</div>
					{% endif %}
					{% if entry.reorder_quantity %}
						<div class="cell qty">{{ entry.reorder_quantity }}</div>
					{% else %}
						<div class="cell qty">&nbsp;</div>
					{% endif %}
					<div class="cell name unit">{{ entry.item.unit }}</div>
					<div class="cell name">{{ entry.item.name }}</div>
				</div>
				{% endfor %}
			{% endfor %}
		</div>
		<script src="{{ STATIC_URL }}js-plugin/jquery-1.7.1.min.js"></script>
		<script src="{{ STATIC_URL }}js/inventory_code.js"></script>
	</body>
</html>

inventory2share/templates/old_inventario.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<meta content="text/html; charset=ISO-8859-1" http-equiv="content-type">
		<title>Inventario</title>
	</head>
	<body>
		<h1>Inventario</h1>
		
		<FORM action="." method="POST">
			{% csrf_token %}
			{{ form.non_field_errors }}
			
			<div class="fieldWrapper">
		        {{ form.name.errors }}
		        <label for="id_name">Inventory Name:</label>
		        {{ form.name }}
		        {{ form.items }}
    		</div>
    		
    		
    		<p>
				<input type="submit" value="Submit">
			</p>
			<p>
				<input type="submit" name="SubmitTpl" value="Save as Template" >
			</p>
		</FORM>
		
		<hr />
		
		
		<h1>Inventario</h1>
		<br>
		<FORM action="/addinv.do/" method="POST">
			{% csrf_token %}
			{% for item in items %}
			<br>
				<INPUT type="checkbox" name="items" value="{{item.id}}">
				<INPUT type="text" name="qty_{{item.id}}" value="3">
				({{ item.unit }})
				{{ item }}
			</br>
			{% endfor %}
			<p>
				<input type="submit" value="Submit">
			</p>
		</FORM>
		
		<hr/>		
		<table>{{ form.as_table }}</table>		
		<hr />
		
		<h1>Contact us</h1>
		<form action="." method="POST">
			{% csrf_token %}
			
				
				<!--
				{{ entryform.as_table }}
				 -->
				 <!--
				{% for item in items %}
				<tr>
				<td>XXX <INPUT type="checkbox" name="inventory_items" value="{{item.id}}">{{ item }}</td>
				</tr>
				{% endfor %}
				-->	
			
			<p>
				<input type="submit" value="Submit">
			</p>
			<p>
				<input type="submit" name="SubmitTpl" value="Save as Template" >
			</p>
		</form>
		
	</body>
</html>

inventory2share/templates/shoppinglist_new.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<link href="{{ STATIC_URL }}css/shopping.css" rel="stylesheet">
		<title>Shopping List</title>
	</head>
	<body>
		<h3>Creating new Shopping List</h3>
		<br />
		<div id="submit_shopping">Submit</div>
		<div id="left" class="left pane">		
			{% for category, items in categories.items %}
			<div class="category" id="L{{ category.id }}">
				<div  class="header">
					{{ category.name }}
				</div>
				{% for item in items %}
				<div class="item" id="{{ category.id }}_{{ item.id }}">
						{{ item.name }}
				</div>
				{% endfor %}
			</div>
			{% endfor %}
		</div>
		<div id="right" class="right pane">
			{% for category, items in categories.items %}
			<div class="category" id="R{{ category.id }}">
				<div  class="header">
					{{ category.name }}
				</div>
			</div>
			{% endfor %}
		</div>
		<script src="{{ STATIC_URL }}js-plugin/jquery-1.7.1.min.js"></script>
		<script src="{{ STATIC_URL }}js-plugin/jquery.json-2.3.min.js"></script>
		<script src="{{ STATIC_URL }}js/shopping_list.js"></script>				
	</body>
</html>

inventory2share/templates/shoppinglist_pick.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<script src="{{ STATIC_URL }}js-plugin/jquery-1.7.1.min.js"></script>
		<script src="{{ STATIC_URL }}js/inventory_code.js"></script>
		<style type="text/css">
		div {
			display: inline;
		}
		</style>
		<title>Shopping List</title>
	</head>
	<body>
		<h1>View Shopping List</h1>
		<ul>
		{% for sl in sls %}
			<li>			
				<a href="/shoppinglist/view/{{ sl.id }}">AA {{ sl }}</a>
			</li>
		{% endfor %}
		</ul>
	</body>
</html>

inventory2share/templates/shoppinglist_view.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<link href="{{ STATIC_URL }}css/inventory.css" rel="stylesheet">
		<link href="{{ STATIC_URL }}css/inventory_print.css" rel="stylesheet"
				media="print" title="Printer-Friendly Style">
		<title>Shopping List</title>
	</head>
	<body id="inventario_view">
		<h2>Shopping List: {{ sl.name }}</h2>
		<form action="." method="GET" id="inventory_view"> 
			<input type="submit" value="Toggle units" id="units">
			<input type="submit" value="Toggle qty" id="qty">
		</form>
		<br/>
		
		<div id="container" class="table_container">
			<div class="row" id="header">
				<span class="cell qty">Qty</span>
				<span class="cell unit">Unit</span>
				<span class="cell name">Name</span>
			</div>
			
			{% for category, entries in results.items %}
				<div  class="row" id="header">
					<div class="cell left qty">&nbsp;</div>
					<div class="cell middle unit">&nbsp;</div>
					<div class="cell right">{{ category.name }}</div>
				</div>
				{% for entry in entries %}					
				<div class="row" id="entry_frame_{{item.id}}">
					{% if entry.quantity %}
						<div class="cell qty">{{ entry.exist_quantity }}</div>
					{% else %}
						<div class="cell qty">&nbsp;</div>
					{% endif %}
					<div class="cell name unit">{{ entry.item.unit }}</div>
					<div class="cell name">{{ entry.item.name }}</div>
				</div>
				{% endfor %}
			{% endfor %}
		</div>
		<script src="{{ STATIC_URL }}js-plugin/jquery-1.7.1.min.js"></script>
		<script src="{{ STATIC_URL }}js/inventory_code.js"></script>
	</body>
</html>